server:
  port: 3333

spring:
  application:
    name: cdforum-util

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: CD-UTIL3333
    prefer-ip-address: true     #访问路径可以显示IP地址