server:
  port: 9527

spring:
  application:
    name: cdforum-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept
  prefix: /cd   #统一前缀
  ignored-services: "*" # 原真实服务名忽略，多个用"*" ignored-services: "*" 要用小写，禁用真名字
  routes:
    cdforum-manManager.serviceId: cdforum-manManager # 真实的微服务名称
    cdforum-manManager.path: /man/** # 假名字，这里做了一个映射

#    cdforum-util.serviceId: cdforum-util # 真实的微服务名称
#    cdforum-util.path: /man/** # 假名字，这里做了一个映射


info:
  app.name: cd
  company.name: www.cd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


